version: '3'
services:
 producer:
    build: .
    container_name: producer
    ports:
      - "8080:8080"
    environment:
        - SPRING_RABBITMQ_HOST=rabbitmq_server
    depends_on:
      - rabbitmq_server
    
 rabbitmq_server:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_server
    
    ports:
      - 5672:5672
      - 15672:15672